projekt/yourtravel/src/main/java/pl/yourtravel/yourtravel/domain/Client.java
package pl.yourtravel.yourtravel.domain;

import java.util.ArrayList;


import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;


import javax.validation.constraints.Size;

@Entity
@NamedQueries({ 
	@NamedQuery(name = "client.all", query = "Select c from Client c")
})
public class Client {

	private Long id;
	private String firstName = "unknown";
	private String surName = "unknown";
	private Long pesel;

	
	private List<Plane> planes = new ArrayList<Plane>();

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	
	@Size(min = 2, max = 20)
	public String getFirstName() {
		return firstName;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}


	// Be careful here, both with lazy and eager fetch type
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	public List<Plane> getPlane() {
		return planes;
	}
	public void setPlane(List<Plane> planes) {
		this.planes = planes;
	}
	public String getSurName() {
		return surName;
	}
	public void setSurName(String surName) {
		this.surName = surName;
	}
	public Long getPesel() {
		return pesel;
	}
	public void setPesel(Long pesel) {
		this.pesel = pesel;
	}
}

projekt/yourtravel/src/main/java/pl/yourtravel/yourtravel/domain/Plane.java
package pl.yourtravel.yourtravel.domain;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
@Entity
@NamedQueries({ 
	@NamedQuery(name = "plane.available", query = "Select f from Plane f")
})
public class Plane {

	private Long id;
	private String name="";
	private int cena;
	

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	
	public int getCena() {
		return cena;
	}
	public void setCena(int cena) {
		this.cena = cena;
	}
	
	
}

projekt/yourtravel/src/main/java/pl/yourtravel/yourtravel/web/ClientFormBean.java
package pl.yourtravel.yourtravel.web;

import java.io.Serializable;

import javax.enterprise.context.SessionScoped;
import javax.faces.model.ListDataModel;
import javax.inject.Inject;
import javax.inject.Named;


import pl.yourtravel.yourtravel.domain.Client;
import pl.yourtravel.yourtravel.domain.Plane;
import pl.yourtravel.yourtravel.service.ClientManager;
import pl.yourtravel.yourtravel.service.OrderingManager;


@SessionScoped
@Named("clientBean")
public class ClientFormBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private Client client = new Client();
	private ListDataModel<Client> clients = new ListDataModel<Client>();
	
	private Client clientToShow = new Client();
	private ListDataModel<Plane> ownedPlane = new ListDataModel<Plane>();


	@Inject
	private ClientManager pm;
	
	@Inject
	private OrderingManager om;

	public Client getClient() {
		return client;
	}
	public void setClient(Client client) {
		this.client = client;
	}
	
	public ListDataModel<Client> getAllClients() {
		clients.setWrappedData(pm.getAllClients());
		return clients;
	}
	
	public ListDataModel<Plane> getOwnedPlane() {
		ownedPlane.setWrappedData(pm.getOwnedPlane(clientToShow));
		return ownedPlane;
	}
	
	// Actions
	public String addClient() {
		pm.addClient(client);
		return "showClients";
	}

	public String deleteClient() {
		Client clientToDelete = clients.getRowData();
		pm.deleteClient(clientToDelete);
		return null;
	}
	
	public String showDetails() {
		clientToShow = clients.getRowData();
		return "details";
	}
	
	public String returnPlane(){
		Plane planeToReturn = ownedPlane.getRowData();
		om.returnPlane(clientToShow, planeToReturn);
		return null;
	}
}

projekt/yourtravel/src/main/java/pl/yourtravel/yourtravel/web/OrderFormBean.java
package pl.yourtravel.yourtravel.web;
import java.io.Serializable;
import java.util.List;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

import pl.yourtravel.yourtravel.domain.Client;
import pl.yourtravel.yourtravel.domain.Plane;
import pl.yourtravel.yourtravel.service.ClientManager;
import pl.yourtravel.yourtravel.service.OrderingManager;

@SessionScoped
@Named("orderBean")
public class OrderFormBean implements Serializable {

	private static final long serialVersionUID = 1L;

	@Inject
	private OrderingManager om;
	@Inject
	private ClientManager pm;

	private Long planeId;
	private Long clientId;
	
	public Long getplaneId() {
		return planeId;
	}
	public void setplaneId(Long planeId) {
		this.planeId = planeId;
	}
	public Long getClientId() {
		return clientId;
	}
	public void setClientId(Long clientId) {
		this.clientId = clientId;
	}

	public List<Plane> getAvailablePlane() {
		return om.getAvailablePlane();
	}

	public List<Client> getAllClients() {
		return pm.getAllClients();
	}

	public String buyTicket() {
		om.buyTicket(clientId, planeId);
		return "showClients";
	}
}

projekt/yourtravel/src/main/java/pl/yourtravel/yourtravel/web/PlaneBean.java
package pl.yourtravel.yourtravel.web;

import java.io.Serializable;

import javax.enterprise.context.SessionScoped;
import javax.faces.model.ListDataModel;
import javax.inject.Inject;
import javax.inject.Named;

import pl.yourtravel.yourtravel.domain.Plane;
import pl.yourtravel.yourtravel.service.PlaneManager;

@SessionScoped
@Named("planeBean")
public class PlaneBean implements Serializable {

	private static final long serialVersionUID = 1L;
	
	private Plane plane = new Plane();
	private ListDataModel<Plane> planes = new ListDataModel<Plane>();
	

	@Inject
	private PlaneManager pm;

	public Plane getPlane() {
		return plane;
	}
	public void setPlane(Plane plane) {
		this.plane = plane;
	}
	
	// Actions
	public ListDataModel<Plane> getAllPlane() {
		planes.setWrappedData(pm.getAllPlane());
		return planes;
	}
}

projekt/yourtravel/src/main/webapp/add.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:p="http://primefaces.org/ui"  
	xmlns:rich="http://richfaces.org/rich">
	

	<ui:define name="content">
		<h:form id="form">  
  
    <p:panel id="panel" header="New Passager">  
  
        <p:messages id="msgs"/>  
  
        <h:panelGrid columns="3">  
            <h:outputLabel for="firstname" value="Firstname: *" />  
            <p:inputText id="firstname" value="#{clientBean.client.firstName}" required="true" label="Firstname">  
                <f:validateLength minimum="2" />  
            </p:inputText>  
            <p:message for="firstname" display="icon"/>  
  
            <h:outputLabel for="surname" value="Surname: *" />  
            <p:inputText id="surname" value="#{clientBean.client.surName}" label="Surname" required="true">  
                <f:validateLength minimum="2" />  
                <p:ajax update="msgSurname" event="keyup" />  
            </p:inputText>  
            <p:message for="surname" id="msgSurname" display="icon"/>  
  
  			  <h:outputLabel for="pesel" value="Pesel: *" />  
            <p:inputText id="pesel" value="#{clientBean.client.pesel}" label="Pesel" required="true">  
                <f:validateLength minimum="8" />  
            </p:inputText>  
            <p:message for="pesel" id="msgPesel" display="icon"/> 
        </h:panelGrid>  
        
      		
        <p:commandButton id="btn" value="Save" update="panel" actionListener="#{clientBean.addClient}" action="showClients?faces-redirect=true"/>  
    </p:panel>  
  
</h:form>  
	
	
	
	
	
	</ui:define>
</ui:composition>

projekt/yourtravel/src/main/webapp/details.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui" 
	template="/templates/default.xhtml">

	<ui:define name="content">
		<h:form prependId="false">  
  
    <p:dataTable id="dataTable" var="item" value="#{clientBean.ownedPlane}">  
  
        <f:facet name="header"> Zamowione przeloty </f:facet>  
  
        <p:column>  
            <f:facet name="header"> Nazwa </f:facet>  
  
            <h:outputText value="#{item.name}" />  
            
        </p:column>  
  		<p:column>  
            <f:facet name="header"> Cena </f:facet>  
  
            <h:outputText value="#{item.cena}" />  
            
        </p:column>  
        <p:column>  
           <f:facet name="header">#{msg.action}</f:facet>
		 <p:commandButton id="btn" icon="ui-icon-close"  actionListener="#{clientBean.returnPlane()}" action="details?faces-redirect=true"/>
          </p:column> 
           
    </p:dataTable>  
  
</h:form>  

	</ui:define>

</ui:composition>


	

projekt/yourtravel/src/main/webapp/home.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml">
	<ui:define name="content">
		<p>#{msg.applicationInfo}</p>
		<p>
        <br /> We'd like to introduce to you this application that lets you manage your planes and passengers. Good luck comrades !! <br /> 
		</p>
		
	</ui:define>
</ui:composition>

projekt/yourtravel/src/main/webapp/index.jsp
<% response.sendRedirect("home.jsf"); %>

projekt/yourtravel/src/main/webapp/order.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich">

	<ui:define name="content">
		<h:form id="personForm">
			<h:panelGrid columns="2">

				<h:outputText value="Klient" />
				<h:selectOneMenu value="#{orderBean.clientId}">
					<f:selectItems value="#{orderBean.allClients}" var="client"
						itemValue="#{client.id}" itemLabel="#{client.firstName}" />
				</h:selectOneMenu>

				<h:outputText value="Przeloty" />
				<h:selectOneMenu value="#{orderBean.planeId}">
					<f:selectItems value="#{orderBean.availablePlane}" var="plane"
						itemValue="#{plane.id}" itemLabel="#{plane.name} #{plane.cena}" />
				</h:selectOneMenu>


			</h:panelGrid>

			<h:commandButton value="Zamow Bilet" action="#{orderBean.buyTicket}" />

			<h:panelGrid>
				<h:messages id="messages" showDetail="#{true}"
					showSummary="#{false}" />
			</h:panelGrid>

		</h:form>

	</ui:define>
</ui:composition>

projekt/yourtravel/src/main/webapp/showClients.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui" 
	template="/templates/default.xhtml">

	<ui:define name="content">
	
	<h:form prependId="false">  
  
    <p:dataTable id="dataTable" var="item" value="#{clientBean.allClients}">  
  
        <f:facet name="header">  #{msg.personAllLabel}  </f:facet>  
  
        <p:column>  
            <f:facet name="header"> #{msg.personFirstNameLabel} </f:facet>  
  
            <h:outputText value="#{item.firstName}" />  
            
        </p:column>  
  		<p:column>  
            <f:facet name="header"> #{msg.personSurNameLabel} </f:facet>  
  
            <h:outputText value="#{item.surName}" />  
            
        </p:column>  
        <p:column>  
            <f:facet name="header"> #{msg.personPeselLabel} </f:facet>  
  
            <h:outputText value="#{item.pesel}" />  
            
        </p:column> 
        
        <p:column>  
            <f:facet name="header"> Details </f:facet>  
  
             <p:commandButton id="btn" icon="ui-icon-star"  actionListener="#{clientBean.showDetails}" action="details?faces-redirect=true"/>
            
        </p:column> 
  
      <!--   <p:column headerText="Details">  
           <h:commandLink value="details" action="#{clientBean.showDetails}"/>  
            
            <p:commandButton action="#{clientBean.showDetails}" id="iconOnly"  
            icon="ui-icon-star" title="Icon Only"/> 
            
             <p:commandButton id="btn" value="Save" update="panel" actionListener="#{clientBean.addClient}" action="showClients?faces-redirect=true"/>  
        </p:column>   -->
          
          
    </p:dataTable>  
  
</h:form>  
	</ui:define>

</ui:composition>

projekt/yourtravel/src/main/webapp/showPlane.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui" 
	template="/templates/default.xhtml">

	<ui:define name="content">
	
	<h:form prependId="false">  
  
    <p:dataTable id="dataTable" var="item" value="#{planeBean.allPlane}">  
  
        <f:facet name="header">  #{msg.planeAll}  </f:facet>  
  
        <p:column>  
            <f:facet name="header"> #{msg.planeId} </f:facet>  
  
            <h:outputText value="#{item.id}" />  
            
        </p:column>  
  
        <p:column headerText="Name">  
            <h:outputText value="#{item.name}" />  
        </p:column>  
  
        <p:column headerText="Cena">  
            <h:outputText value="#{item.cena}" />  
        </p:column>  
          
          
    </p:dataTable>  
  
</h:form>  
	</ui:define>

</ui:composition>

projekt/yourtravel/src/main/webapp/templates/default.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title><ui:insert name="windowTitle">#{msg.mainWindowTitle}</ui:insert></title>
	
</h:head>
<h:body>
	<h:outputStylesheet library="css" name="style.css" target="body" />
	<div id="container">
		<div id="logo">
		</div>
		<div id="left">
			<div id="menu2">
			<ui:insert name="menu">
         <ui:include src="/views/main/menu.xhtml" />
       </ui:insert>
				
			</div>
			
			<div class="clear">&nbsp;</div>
		</div>
		<div id="right">
			<div id="tresc">
				<div class="nagl">#{msg.mainHeading}</div>
				<ui:insert name="content" />
			</div>
		</div>
		<div id="stopka">All right reserved</div>
	</div>
</h:body>
</html>

projekt/yourtravel/src/main/webapp/views/main/menu.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"  
	xmlns:h="http://java.sun.com/jsf/html">
 	
  <h:form>  
              
    <p:growl id="messages"/>  
     
    
    <p:slideMenu style="width:200px;height:310px">  
    
    	         <p:submenu label="Ticket" icon="ui-icon-star">  
            <p:menuitem value="New Passager" action="add" update="messages" icon="ui-icon-disk"/>  
            <p:menuitem value="Show" action="showClients" update="messages" icon="ui-icon-arrowrefresh-1-w"/>
 			<p:menuitem value="Book a ticket" action="order"  update="messages" icon="ui-icon-extlink"/> 	       
        </p:submenu>  
        <p:submenu label="Show departures" icon="ui-icon-home">  
            <p:menuitem value="Flights"   ajax="false" action="showPlane" icon="ui-icon-arrowrefresh-1-w"/>  
        </p:submenu>  
        <p:submenu label="Links" icon="ui-icon-extlink">  
            
                <p:menuitem value="Lot" url="http://www.lot.com" />  
                <p:menuitem value="Wizzair" url="http://wizzair.com" /> 
                <p:menuitem value="Emirates" url="www.emirates.com/‎" />
                <p:menuitem value="BritishAirWays" url="www.britishairways.com/" /> 
           		<p:menuitem value="Lufthansa" url="www.lufthansa.com/" />
       
        </p:submenu>  
    </p:slideMenu>  
  
</h:form>  
</ui:composition>